import '../styles/globals.css';
import ToasterContext from './context/ToasterContext';
import AuthContext from './context/AuthContext';

export const metadata = {
  title: 'ChatMessage',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthContext>
          <ToasterContext />
          {children}
        </AuthContext>
      </body>
    </html>
  )
}
